version: "3"

services:
  azure-poc:
    image: azure-poc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      REACT_APP_AUTHORITY: ${REACT_APP_AUTHORITY}
      REACT_APP_CLIENT_ID: ${REACT_APP_CLIENT_ID}
    ports:
      - "3000:3000"
